seajs.config({
    //设置路径方便夸目录调用
    base:Context.PATH+"/",
    alias:{
        "jquery" : Context.PATH+"/js/lib/jquery/1.10.1/jquery.js",
      //  "data-dispose": Context.PATH+"/js/data-dispose",
      //  "global" : Context.PATH+"/js/global",
        "jquery-tips" : "js/plugin/jquery-tips.js",
        "checkformtips" : Context.PATH+"/js/event/checkformtips.js",
        "prcsteel" : Context.PATH+"/js/plugin/prcsteel.js",
        "shoppingcart": Context.PATH+"/js/plugin/jquery.shoppingcart.sea.js",
        "json": Context.PATH+"/js/plugin/jquery.json.sea.js",
        "store" : Context.PATH+"/js/plugin/store.sea.js",
        "gwfind":Context.PATH+"/js/plugin/jquery.gwfind.sea.js",
        "cart":Context.PATH+"/js/plugin/jquery.cart.sea.js",
        "sendsms" : Context.PATH+"/js/plugin/sendsms.js",
        "member" : Context.PATH+"/js/module/member.js",
        "requirement":Context.PATH+"/js/module/requirement.js",
        "util" : Context.PATH+"/js/util.js",
        "caslogin" : Context.PATH+"/js/plugin/caslogin.js",
        "constant" : Context.PATH+"/js/constant.js",
        "consign":Context.PATH+"/js/module/consignmanage.js",
        "jqueryMigrate": Context.PATH+"/js/plugin/jquery-migrate-1.1.0.js",
        "jqprint":Context.PATH+"/js/plugin/jquery.jqprint-0.3.js",
        "index":Context.PATH+"/js/module/index.js",
	 	"cache":Context.PATH+"/js/cache.js",
        "indexsearch" : Context.PATH+"/js/event/index.search.js",
        "cas" : Context.PATH+"/js/cas.js",
        "ajax.remote.login" : Context.PATH+"/js/event/ajax.remote.login.js",
        "jquery1.9" : Context.PATH+"/js/lib/jquery/1.9.0/jquery.js",
        "gwfind.dialog" : Context.PATH+"/js/event/gwfind.dialog.js",
        "ajaxfileupload" : Context.PATH+"/js/plugin/jquery.ajaxfileupload.js",
        "helpfind" : Context.PATH+"/js/module/helpfind.js",
        'event.shoppingcart' : Context.PATH+'/js/event/shoppingcart.js',
        "module.indexslide" : Context.PATH+'/js/module/indexslide.js',
        "json2" : Context.PATH+"/js/plugin/json2.js",
        "usercallback" : Context.PATH+"/js/callback/usercallback.js",
        "search" :  Context.PATH+"/js/searchMarket.js",
        "markethelpfind" :  Context.PATH+"/js/module/markethelpfind.js",
        "sendsmscallback" :  Context.PATH+"/js/callback/sendsmscallback.js",
        "jquery-page" : Context.PATH+"/js/plugin/jquery-page.js",
        "artdialog.min" : Context.PATH+"/js/plugin/artdialog.min.js",
        "find.init" : Context.PATH+"/js/event/find.int.js",
        "about" : Context.PATH+"/js/about.js",
        "ad" : Context.PATH+"/js/adintro.js",
        "land" : Context.PATH+"/js/module/land.js",
        "nav" : Context.PATH+"/js/nav.js",
        "land234":Context.PATH+"/js/land-234.js"
    }
});
       