package com.prcsteel.ec.model.domain.ec;

// default package
// Generated April 19, 2016 11:32:10 AM by Hibernate Tools 3.4.0.CR1

import com.prcsteel.ec.model.annotations.Column;
import com.prcsteel.ec.model.annotations.Entity;
import com.prcsteel.ec.model.annotations.KeyColumn;
import com.prcsteel.ec.model.common.DataEntity;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import javax.validation.constraints.Pattern;
import java.util.Date;

/**
 * Demo generated by hbm2java
 */
@Entity("demo")
public class Demo extends DataEntity<Demo> {

	private static final long serialVersionUID = 1L;

	@KeyColumn(useGeneratedKeys=true)
	@Column(value = "id")
	private Integer id;

	@Column(value = "account")
	@NotEmpty(message = "账号不能为空。")
	private String account;

	@Column(value = "password")
	@Length(min = 8, max = 15, message = "密码长度不能小于8位且不能大于15位。")
	@Pattern(regexp = "^[A-Za-z0-9]*$", message = "密码必须是字母或数字")
	private String password;

	@Column(value = "email")
	private String email;

	public Demo(){

	}

	public Demo(String account, String password, String email, Date gmtCreated, Date gmtModified) {
		this.account = account;
		this.password = password;
		this.email = email;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
}
